[package]
name = "thrm_ex"
version = "0.2.0"
edition = "2021"

[dependencies]
confy = "*"
serde = { version = "*", features = ["derive"] }
windows = {version = "*", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"]}