[package]
name = "thrm_ex"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "*", features = ["Win32_Foundation", "Win32_Graphics_Dwm", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"]}